InternshipProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('oldstimes/', include('old_straits_times.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

old_straits_times/urls.py
from django.urls import path
from . import views

app_name = 'oldstimes'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<slug:author_username>', views.profile, name='profile'),
    path('category', views.category, name='category'),
    path('search', views.search, name='search'),

    path('story/<int:story_id>', views.story, name='story'),
    path('story/<int:story_id>/edit', views.story_edit, name='story_edit'),
    path('post', views.story_post, name='story_post'),

    path('auth/login', views.auth_login, name='auth_login'),
    path('auth/logout', views.auth_logout, name='auth_logout'),
    path('register', views.auth_register, name='register'),

    path('settings/profile', views.settings_profile, name='settings_profile'),
    path('settings/manage', views.settings_manage, name='settings_manage'),
    path('settings/theme', views.settings_theme, name='settings_theme')
]

old_straits_times/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxLengthValidator
from django.db.models import Q
from django.forms import ModelForm
from ckeditor.fields import RichTextField
from django_resized import ResizedImageField

import re
import os
from uuid import uuid4

from django.utils.deconstruct import deconstructible

@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)

path_and_rename = PathAndRename("old_straits_times/avatars")

# Create your models here.
class Author(AbstractUser):
    bio = RichTextField()
    country = models.CharField(max_length=60, default="", blank=True, null=True)
    avatar = ResizedImageField(size=[400,400],
                               default="avatars/none/default.png",
                               upload_to=path_and_rename,
                               null=True,
                               blank=True)
    
    social1 = models.CharField(max_length=120, default="", blank=True, null=True)
    social2 = models.CharField(max_length=120, default="", blank=True, null=True)
    social3 = models.CharField(max_length=120, default="", blank=True, null=True)
    social4 = models.CharField(max_length=120, default="", blank=True, null=True)
    
    def stories(self):
        return Story.objects.filter(author=self.pk).order_by('-date_published')
    
    def stories_count(self):
        return self.stories().count()
    
    def total_views(self): 
        return sum([story.views_total for story in self.stories()])
    
class Genre(models.Model):
    name = models.CharField(max_length=30)
    
    def stories_count(self):
        return Story.objects.filter(genre=self.pk).count()
    
    def __str__(self) -> str:
        return self.name

class Story(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    genre = models.ManyToManyField(Genre, blank=True)
    abstract = models.TextField(max_length=250, blank=True,
                                   validators=[MaxLengthValidator(250)])
    date_published = models.DateTimeField('date published', auto_now_add=True)
    date_last_updated = models.DateTimeField('date last updated')
    views_total = models.IntegerField(default=0)
    is_private = models.BooleanField(default=False)
    content = RichTextField()
    
    def comments(self):
        return Comment.objects.filter(story=self.pk, reply_to=None).order_by('-date_published')
    
    def get_views_total(self):
        return f'{self.views_total:3}'
    
    def get_word_count(self):
        return len(re.sub(r'<.*?>||&.*?;||^\n', '', self.content).strip())
    
    def get_reading_time_taken(self):
        return round(self.get_word_count() / 200, 2)
    
    def get_genre(self):
        return ", ".join([s.name for s in self.genre.all()])
    get_genre.short_description = 'Genre'
    
    def __str__(self) -> str:
        return self.title
    
class Comment(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    commenter = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL)
    reply_to = models.ForeignKey('Comment', null=True, blank=True, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    date_published = models.DateTimeField('date published', auto_now_add=True)
    edited = models.BooleanField(default=False)
    likes = models.ManyToManyField(Author, blank=True, related_name='likeses')
    dislikes = models.ManyToManyField(Author, blank=True, related_name='dislikeses')
    
    def replies(self):
        return Comment.objects.filter(reply_to=self)

class StoryForm(ModelForm):
    class Meta:
        model = Story
        fields = [
            'title',
            'genre',
            'abstract',
            'content',
            'is_private',
        ]

class ProfileForm(ModelForm):
    class Meta:
        model = Author
        fields = [
            'email',
            'avatar',
            'bio',
            'first_name',
            'last_name',
            'country',
            'social1',
            'social2',
            'social3',
            'social4'
        ]

old_straits_times/views/settings.py
import datetime
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from ..models import ProfileForm, Story, Author

def set_cookie(response, key, value, days_expire=7):
    if days_expire is None:
        max_age = 365 * 24 * 60 * 60  # one year
    else:
        max_age = days_expire * 24 * 60 * 60
    expires = datetime.datetime.strftime(
        datetime.datetime.utcnow() + datetime.timedelta(seconds=max_age),
        "%a, %d-%b-%Y %H:%M:%S GMT",
    )
    response.set_cookie(
        key,
        value,
        max_age=max_age,
        expires=expires,
        domain=settings.SESSION_COOKIE_DOMAIN,
        secure=settings.SESSION_COOKIE_SECURE or None,
    )

def settings_profile(request):
    template_name = 'old_straits_times/settings/profile.html'
    author = get_object_or_404(Author, pk=request.user.pk)
    
    if request.method == 'POST':
        current_password = request.POST.get('current_password')
        new_password = request.POST.get('new_password')
        new_password_confirmation = request.POST.get('new_password_confirmation')
        
        if current_password and new_password and new_password_confirmation:
            if new_password != new_password_confirmation:
                return render(request, template_name, {
                    "author": author,
                    'error_message': "New password is not same as confirmation!"
                })   
            
            if author.check_password(new_password):
                author.set_password(new_password)
            else:
                return render(request, template_name, {
                    "author": author,
                    'error_message': "Current password is not correct!"
                })       
        
        form = ProfileForm(request.POST, request.FILES, instance=author)
        if form.is_valid():
            avatar_existing = request.POST.get('avatar_existing')
            if avatar_existing != 'true':
                form.instance.avatar = None

            form.save()
        else:
            print(form.errors)
            
        return render(request, template_name, {
            "author": author,
            'success_message': "The profile has been successfully updated."
        })
        
    
    return render(request, template_name, {
        "author": author
    })
    
def settings_theme(request):
    template_name = 'old_straits_times/settings/theme.html'
    
    if request.method == 'POST':
        theme_color = request.POST.get('theme_color')
        request.COOKIES['theme_color'] = theme_color
        response = render(request, template_name, {})
        response.set_cookie('theme_color', theme_color)
        
        return response
    
    return render(request, template_name, {})

def settings_manage(request):
    template_name = 'old_straits_times/settings/manage.html'
    
    if request.method == 'POST':
        post_type = request.POST.get('post_type')
        pk = request.POST.get('pk')
        story = Story.objects.get(pk=pk)
        
        if pk:
            if post_type == 'private' or post_type == 'public':
                story.is_private = post_type == 'private'
                story.save() 
                
                return JsonResponse({
                    'message': f'Published or Privated Story {pk} from table!'
                })
            elif post_type == 'delete':
                story.delete()
                
                return JsonResponse({
                    'message': f'Deleted Story {pk} from table!'
                })
    
    stories = Story.objects.filter(author=request.user).order_by('-date_published')
    return render(request, template_name, {
        'stories': stories
    })
    

old_straits_times/views/story.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.utils import timezone
from django.urls import reverse


from ..models import Story, Genre, Author, Comment, StoryForm


def story(request, story_id):
    story = get_object_or_404(Story, pk=story_id)
    template_name = 'old_straits_times/story/index.html'
    
    # add a view count for each user enter the page
    if story and story.author.pk != request.user.pk:
        story.views_total += 1
        story.save()
        
    if request.method == 'POST':
        post_type = request.POST.get('post_type')
        
        # if post type is to post comment
        if post_type == 'post_comment':
            content = request.POST.get('content')
            
            new_comment = Comment(
                story=story,
                commenter=request.user,
                content=content
            )
            new_comment.save()
            
        elif post_type == 'reply_comment':
            content = request.POST.get('content')
            reply_to = Comment.objects.get(pk=request.POST.get('reply_to'))
            
            new_reply = Comment(
                story=story,
                commenter=request.user,
                content=content,
                reply_to=reply_to
            )
            new_reply.save()
            
            return JsonResponse({'success': 'Replied Sucessfully'}, status=200)
        
        elif post_type == 'like_comment':
            comment_pk = request.POST.get('comment_pk')
            comment = Comment.objects.get(pk=comment_pk)
            
            author = Author.objects.get(pk=request.user.pk)
            if not comment.likes.filter(pk=request.user.pk).exists():
                comment.likes.add(author)
                if comment.dislikes.filter(pk=request.user.pk).exists():
                    comment.dislikes.remove(author)
            else:
                comment.likes.remove(author)
                
            return JsonResponse({
                'message': "Disliked Successfully",
                'like_count': comment.likes.count(),
                'dislike_count': comment.dislikes.count()
            })
            
        elif post_type == 'dislike_comment':
            comment_pk = request.POST.get('comment_pk')
            comment = Comment.objects.get(pk=comment_pk)
            
            author = Author.objects.get(pk=request.user.pk)
            if not comment.dislikes.filter(pk=request.user.pk).exists():
                comment.dislikes.add(author)
                if comment.likes.filter(pk=request.user.pk).exists():
                    comment.likes.remove(author)
            else:
                comment.dislikes.remove(author)
                
            return JsonResponse({
                'message': "Disliked Successfully",
                'like_count': comment.likes.count(),
                'dislike_count': comment.dislikes.count()
            })
    
    return render(request, template_name, {
        'story': story
    })
    
def story_post(request):
    all_genre = Genre.objects.all()
    template_name = 'old_straits_times/story/post.html'
    
    if request.method == 'POST':
        form = StoryForm(request.POST, request.FILES)

        if form.is_valid():
            new_story:Story = form.save(commit=False)

            new_story.author = Author.objects.get(pk=request.user.pk)
            new_story.date_published = timezone.now()
            new_story.date_last_updated = timezone.now()

            new_story.save()

            genre = request.POST.getlist('genre_raw')
            genre_pk = list(map(lambda x: Genre.objects.get(name=x), genre))
            new_story.genre.set(genre_pk)

            return HttpResponseRedirect(reverse('oldstimes:story', kwargs={'story_id': new_story.pk}))
    
    return render(request, template_name, {
        'all_genre': all_genre
    })
    
def story_edit(request, story_id):
    current_story = get_object_or_404(Story, pk=story_id) 
    all_genre = Genre.objects.all()
    template_name = 'old_straits_times/story/edit.html'

    if request.method == 'POST':
        # delete story
        deleteStory = request.POST.get('delete_story')
        if deleteStory == 'true':
            current_story.delete()
            return HttpResponseRedirect(reverse('oldstimes:index'))
        
        # edit story
        form = StoryForm(request.POST, request.FILES, instance=current_story)
        
        if form.is_valid():
            form.save(commit=False)

            current_story.author = Author.objects.get(pk=request.user.pk)
            current_story.date_last_updated = timezone.now()

            current_story.save()

            genre = request.POST.getlist('genre_raw')
            genre_pk = list(map(lambda x: Genre.objects.get(name=x), genre))
            current_story.genre.set(genre_pk)

            return HttpResponseRedirect(reverse('oldstimes:story', kwargs={'story_id': current_story.pk}))

    return render(request, template_name, {
        'all_genre': all_genre,
        'current_story': current_story
    })

old_straits_times/templates/old_straits_times/base.html
<!doctype html>
<html lang="en" data-bs-theme="{{ request.COOKIES.theme_color|default:'light' }}">
    <head>
        <!-- required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Oldstimes{% if title %} - {{ title }}{% endif %}</title>

        {% load static %}
        <!-- bootstrap css -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        
        <!-- css.gg -->
        <link href='https://css.gg/css' rel='stylesheet'>

        {% load sass_tags %}
        <!-- custom styles -->
        <link href="{% sass_src 'old_straits_times/customs.scss' %}" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <header class="sticky-top shadow bg-body">
            <div class="container">
                <div class="py-3 d-flex justify-content-between">
                    <div>
                        <nav>
                            {% comment %} mobile {% endcomment %}
                            <div class="d-md-none">
                                <button class="btn btn-body text-primary-emphasis p-1" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="bi" fill="currentColor" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"></path>
                                      </svg>
                                </button>

                                <button class="btn btn-body text-primary-emphasis p-1 px-2" type="button" data-bs-toggle="modal" data-bs-target="#searchModal">
                                    <i class="bi bi-search"></i>
                                </button>

                                <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
                                <div class="offcanvas-header">
                                    <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Menu</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                                </div>
                                <div class="offcanvas-body">
                                    <ul class="list-unstyled">
                                        <li class="nav-item">
                                            <a href="{% url 'oldstimes:index' %}" class="btn btn-body w-100 text-start" aria-current="page">
                                                <span class="h6 text-decoration-none">Home</span>
                                            </a>
                                        </li>
                                        {% if request.user.is_authenticated %}
                                            <li class="nav-item">
                                                <a href="{% url 'oldstimes:story_post' %}" class="btn btn-body w-100 text-start" aria-current="page">
                                                    <span class="h6 text-decoration-none">Post a Story</span>
                                                </a>
                                            </li>
                                        {% endif %}
                                        <li class="nav-item">
                                            <a class="btn btn-body w-100 text-start" href="{% url 'oldstimes:category' %}">
                                                <span class="h6 text-decoration-none">Category</span>
                                            </a>
                                        </li>  
                                    </ul>
                                </div>
                                </div>
                            </div>
                            {% comment %} desktop {% endcomment %}
                            <ul class="nav d-none d-md-flex">
                                <li class="nav-item">
                                  <a href="{% url 'oldstimes:index' %}" class="nav-link" aria-current="page">Home</a>
                                </li>
                                {% if request.user.is_authenticated %}
                                    <li class="nav-item">
                                        <a href="{% url 'oldstimes:story_post' %}" class="nav-link" aria-current="page">Post a Story</a>
                                    </li>
                                {% endif %}
                                <li class="nav-item">
                                  <a class="nav-link" href="{% url 'oldstimes:category' %}">Category</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="d-none d-md-block d-lg-none">
                        <button class="btn btn-outline-secondary text-start" data-bs-toggle="modal" data-bs-target="#searchModal">
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                    <div class="d-none d-lg-block">
                        <div class="d-flex" role="search">
                            <button class="btn btn-outline-secondary text-start" data-bs-toggle="modal" data-bs-target="#searchModal" style="width: 275px;">
                                <i class="bi bi-search"></i>
                                Search
                            </button>
                        </div>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="d-flex align-items-center">
                            <span class="pe-3">Hello <a href="{% url 'oldstimes:profile' request.user.username %}">{{ request.user.username }}</a></span>
                            <a class="pe-3" href="{% url 'oldstimes:settings_profile' %}">
                                Settings
                            </a>
                            <a class="d-none d-sm-block" href="{% url 'oldstimes:auth_logout' %}">
                                <button class="btn btn-outline-primary">Sign Out</button>
                            </a>
                        </div>
                    {% else %}
                        <div class="d-flex align-items-center text-body">
                            <span class="pe-3">Hello Guest</span>
                            <a href="{% url 'oldstimes:auth_login' %}">
                                <button class="btn btn-outline-primary">Sign in</button>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </header>

        <!-- ckeditor js -->
        <script src="https://cdn.ckeditor.com/4.20.2/full/ckeditor.js"></script>

        <div class="container my-4">
            {% block content %}{% endblock content %}
        </div>

        <!-- bootstrap javascript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <script>
            const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
            const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
        </script>

        <!-- ckeditor javascript -->
        <script>
            const ckBodyStyle = getComputedStyle(document.body);
            const ckBodyBG = ckBodyStyle.getPropertyValue('--bs-body-bg')
            const ckBodyColor = ckBodyStyle.getPropertyValue('--bs-body-color')
            
            CKEDITOR.addCSS
            CKEDITOR.addCss(`.cke_editable { background-color: ${ckBodyBG}; color: ${ckBodyColor}; }`);
        </script>

        <!-- js-cookie javascript -->
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    </body>

    <!-- Search Modal -->
    <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="searchModalLabel"><i class="bi bi-search me-2"></i>Search</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body pb-0">
                <div class="input-group">
                    <input name="search_query" id="searchInput" type="text" class="form-control" placeholder="Search here...">
                </div>
                <div id='resultPanel' class="row gy-3 py-3 mx-0"></div>
            </div>
        </div>
        </div>
    </div>

    <script>
        const searchItem = ({pk, title, genre, author}) => `
        <a class="p-0 text-muted text-decoration-none" href="/oldstimes/story/${pk}">
            <div class="col p-2 card">
                <h6 class="mb-3">${title}</h6>
                <div class="d-flex justify-content-between">
                    <p class="fs-7 mb-0">${genre}</p>
                    <p class="fs-7 mb-0">${author}</p>
                </div>
            </div>
        </a>
        `

        const noResult = `
        <div class="py-2">
            <div class="text-center mb-3">
                <svg width="40" height="40" viewBox="0 0 20 20" fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M15.5 4.8c2 3 1.7 7-1 9.7h0l4.3 4.3-4.3-4.3a7.8 7.8 0 01-9.8 1m-2.2-2.2A7.8 7.8 0 0113.2 2.4M2 18L18 2"></path></svg>
            </div>
            <h6 class="text-center">No result for the search...</h6>
        </div>
        `

        let typingTimer;                //timer identifier
        let doneTypingInterval = 500;  //time in ms (1 second)
        const searchInputEl = document.getElementById('searchInput')
        const resultPanelEl = document.getElementById('resultPanel')   
        const csrftoken = Cookies.get('csrftoken')

        const doneTyping = () => {
            const data = new FormData()

            data.set('search_query', searchInputEl.value)

            fetch("{% url 'oldstimes:search' %}", {
                method: 'POST',
                mode: "same-origin",
                headers: { "X-CSRFToken": csrftoken },
                body: data
            })
            .then(res => res.json().then(data => {
                const result = JSON.parse(data.result)

                let resultEl = ''
                if (result instanceof Array && result.length != 0) {
                    result.map(value => resultEl += searchItem({
                        pk: value.pk,
                        title: value.title,
                        genre: value.genre,
                        author: value.author
                    }))
                } else {
                    resultEl = noResult
                }
                resultPanelEl.innerHTML = resultEl
            }))
            .catch(err => console.log(err))
        }

        searchInputEl.addEventListener('keyup', () => {
            clearTimeout(typingTimer);
            if (searchInputEl.value) {
                typingTimer = setTimeout(doneTyping, doneTypingInterval);
            }
        })

        const searchModalEl = document.getElementById('searchModal')
        searchModalEl.addEventListener('shown.bs.modal', event => {
            searchInputEl.focus()
        })
    </script>
</html>

old_straits_times/templates/old_straits_times/settings_base.html
{% extends './base.html' %}

{% block content %}
    <h1 class="mb-4">Settings</h1>
    <div class="row">
        <div class="col-12 col-lg-3 mb-4">
            <div class="settings-list border rounded p-4">
                <ul class="list-unstyled mb-0">
                    <a href="{% url 'oldstimes:settings_profile' %}"><li>Profile</li></a>
                    <a href="{% url 'oldstimes:settings_theme' %}"><li>Preferences</li></a>
                    <a href="{% url 'oldstimes:settings_manage' %}"><li>Manage Stories</li></a>
                </ul>
                <ul class="list-unstyled mb-0">
                    <a><li>Notifications</li></a>
                    <a><li>Privacy and Security</li></a>
                    <a href="{% url 'oldstimes:auth_logout' %}"><li>Sign out</li></a>
                </ul>
            </div>
        </div>
        <div class="col">{% block sub-content %}{% endblock sub-content %}</div>
    </div>
{% endblock content %}

old_straits_times/templates/old_straits_times/settings_manage.html
{% extends './settings_base.html' %}

{% block sub-content %}
    <h3>Manage your stories</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Story ID</th>
                <th scope="col">Title</th>
                <th scope="col">Publish Date</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for story in stories %}
                <tr id="story-{{ story.pk }}">
                    <td>{{ story.pk }}</td>
                    <td scope="row">
                        <a href="{% url 'oldstimes:story' story.pk %}">{{ story.title }}</a>
                    </td>
                    <td>{{ story.date_published }}</td>
                    <td>
                        <a href="{% url 'oldstimes:story_edit' story.pk %}" class="btn btn-sm btn-outline-primary">Edit</a>
                        <button class="btn btn-sm btn-outline-danger" onclick="changeStory({{ story.pk }}, 'delete')">Delete</button>
                        <button id="private-{{ story.pk }}" class="btn btn-sm btn-outline-warning {% if story.is_private %}d-none{% endif %}" onclick="changeStory({{ story.pk }}, 'private')">Private</button>
                        <button id="public-{{ story.pk }}" class="btn btn-sm btn-outline-info {% if not story.is_private %}d-none{% endif %}" onclick="changeStory({{ story.pk }}, 'public')">Public</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
        const changeStory = (storyPK, type) => {
            const privateEl = document.getElementById(`private-${storyPK}`)
            const publicEl = document.getElementById(`public-${storyPK}`)

            const data = new FormData()
            data.set('pk', storyPK)
            data.set('post_type', type)

            if (confirm(`Are you sure you want to ${type} the story?`)) {
                fetch("{% url 'oldstimes:settings_manage' %}", {
                    method: 'POST',
                    mode: "same-origin",
                    headers: { "X-CSRFToken": csrftoken },
                    body: data
                })
                .then(res => {
                    ({
                        'delete': () => document.getElementById(`story-${storyPK}`).remove(),
                        'private': () => {
                            privateEl.classList.add('d-none')
                            publicEl.classList.remove('d-none')
                        },
                        'public': () => {
                            publicEl.classList.add('d-none')
                            privateEl.classList.remove('d-none')
                        },
                    }[type]())
                })
                .catch(err => console.log(err))
            }
        }
    </script>
{% endblock sub-content %}